version: '3.8'

services:
  signalr-productmanagement:
    image: signalr-productmanagement:latest
    build:
      context: .
      dockerfile: SignalR-ProductManagement/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1400:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Shinjuuichidesu@11
    restart: always
