services:
  signalr-productmanagement:
    image: signalr-productmanagement:latest
    build:
      context: .
      dockerfile: SignalR-ProductManagement/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=SignalR-Product;User Id=sa;Password=Shinjuuichidesu@11;TrustServerCertificate=True
    restart: always
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Shinjuuichidesu@11
    restart: always
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    name: sqlserver-data